// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels(in *jlexer.Lexer, out *OrderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "orderUid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OrderUUID).UnmarshalText(data))
			}
		case "orderItemUid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OrderItemUUID).UnmarshalText(data))
			}
		case "OrderDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.OrderDate).UnmarshalJSON(data))
			}
		case "model":
			out.Model = string(in.String())
		case "size":
			out.Size = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels(out *jwriter.Writer, in OrderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"orderUid\":"
		out.RawString(prefix[1:])
		out.RawText((in.OrderUUID).MarshalText())
	}
	{
		const prefix string = ",\"orderItemUid\":"
		out.RawString(prefix)
		out.RawText((in.OrderItemUUID).MarshalText())
	}
	{
		const prefix string = ",\"OrderDate\":"
		out.RawString(prefix)
		out.Raw((in.OrderDate).MarshalJSON())
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels(l, v)
}
func easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels1(in *jlexer.Lexer, out *AllOrders) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(AllOrders, 0, 0)
			} else {
				*out = AllOrders{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 OrderResponse
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels1(out *jwriter.Writer, in AllOrders) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v AllOrders) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AllOrders) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6f541b9EncodeLab2MicroservicesKTLHInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AllOrders) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AllOrders) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6f541b9DecodeLab2MicroservicesKTLHInternalModels1(l, v)
}
