// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA21e9db7DecodeLab2InternalModels(in *jlexer.Lexer, out *OrderItems) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "cancelled":
			out.Cancelled = bool(in.Bool())
		case "order_item_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OrderItemUuid).UnmarshalText(data))
			}
		case "order_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OrderUuid).UnmarshalText(data))
			}
		case "item_id":
			out.ItemID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA21e9db7EncodeLab2InternalModels(out *jwriter.Writer, in OrderItems) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"cancelled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Cancelled))
	}
	{
		const prefix string = ",\"order_item_uuid\":"
		out.RawString(prefix)
		out.RawText((in.OrderItemUuid).MarshalText())
	}
	{
		const prefix string = ",\"order_uuid\":"
		out.RawString(prefix)
		out.RawText((in.OrderUuid).MarshalText())
	}
	{
		const prefix string = ",\"item_id\":"
		out.RawString(prefix)
		out.Int(int(in.ItemID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OrderItems) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA21e9db7EncodeLab2InternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OrderItems) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA21e9db7EncodeLab2InternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OrderItems) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA21e9db7DecodeLab2InternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OrderItems) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA21e9db7DecodeLab2InternalModels(l, v)
}
