// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEca43ab4DecodeLab2MicroservicesKTLHInternalModels(in *jlexer.Lexer, out *UserOrderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "orderUid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OrderUUID).UnmarshalText(data))
			}
		case "date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Date).UnmarshalJSON(data))
			}
		case "model":
			out.Model = string(in.String())
		case "size":
			out.Size = string(in.String())
		case "warrantyDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.WarrantyDate).UnmarshalJSON(data))
			}
		case "warrantyStatus":
			out.WarrantyStatus = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEca43ab4EncodeLab2MicroservicesKTLHInternalModels(out *jwriter.Writer, in UserOrderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"orderUid\":"
		out.RawString(prefix[1:])
		out.RawText((in.OrderUUID).MarshalText())
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.Raw((in.Date).MarshalJSON())
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	{
		const prefix string = ",\"warrantyDate\":"
		out.RawString(prefix)
		out.Raw((in.WarrantyDate).MarshalJSON())
	}
	{
		const prefix string = ",\"warrantyStatus\":"
		out.RawString(prefix)
		out.String(string(in.WarrantyStatus))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserOrderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEca43ab4EncodeLab2MicroservicesKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserOrderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEca43ab4EncodeLab2MicroservicesKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserOrderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEca43ab4DecodeLab2MicroservicesKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserOrderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEca43ab4DecodeLab2MicroservicesKTLHInternalModels(l, v)
}
