// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels(in *jlexer.Lexer, out *WarrantyResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "date":
			out.Date = string(in.String())
		case "decision":
			out.Decision = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels(out *jwriter.Writer, in WarrantyResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"decision\":"
		out.RawString(prefix)
		out.String(string(in.Decision))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WarrantyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WarrantyResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WarrantyResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WarrantyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels(l, v)
}
func easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels1(in *jlexer.Lexer, out *WarrantyOderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "orderUid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UUID).UnmarshalText(data))
			}
		case "warrantyDate":
			out.Date = string(in.String())
		case "decision":
			out.Decision = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels1(out *jwriter.Writer, in WarrantyOderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"orderUid\":"
		first = false
		out.RawString(prefix[1:])
		out.RawText((in.UUID).MarshalText())
	}
	{
		const prefix string = ",\"warrantyDate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"decision\":"
		out.RawString(prefix)
		out.String(string(in.Decision))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WarrantyOderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WarrantyOderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19a2068EncodeLab2MicroservicesKTLHInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WarrantyOderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WarrantyOderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19a2068DecodeLab2MicroservicesKTLHInternalModels1(l, v)
}
