// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA393ab88DecodeLab2MicroservicesKTLHInternalModels(in *jlexer.Lexer, out *Warranty) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = int(in.Int())
		case "Comment":
			out.Comment = string(in.String())
		case "itemUid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ItemUuid).UnmarshalText(data))
			}
		case "status":
			out.Status = string(in.String())
		case "warrantyDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Warranty).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA393ab88EncodeLab2MicroservicesKTLHInternalModels(out *jwriter.Writer, in Warranty) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"Comment\":"
		out.RawString(prefix)
		out.String(string(in.Comment))
	}
	{
		const prefix string = ",\"itemUid\":"
		out.RawString(prefix)
		out.RawText((in.ItemUuid).MarshalText())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"warrantyDate\":"
		out.RawString(prefix)
		out.Raw((in.Warranty).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Warranty) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA393ab88EncodeLab2MicroservicesKTLHInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Warranty) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA393ab88EncodeLab2MicroservicesKTLHInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Warranty) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA393ab88DecodeLab2MicroservicesKTLHInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Warranty) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA393ab88DecodeLab2MicroservicesKTLHInternalModels(l, v)
}
